#!/usr/bin/env python3
"""PreToolUse hook: block Edit/Write into generated Xcode project bundles.

PlusPlus.xcodeproj is generated by XcodeGen from project.yml and is
gitignored — an edit inside it is always a mistake (it vanishes on the next
`xcodegen` run and never reaches the repo). Exit 2 blocks the tool call and
the stderr message tells the session where the change actually belongs.
"""
import json
import sys


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return  # malformed input: never block on our own bug
    path = (payload.get("tool_input") or {}).get("file_path") or ""
    if ".xcodeproj/" in path or path.endswith(".xcodeproj"):
        print(
            "Blocked: this file is inside a generated .xcodeproj bundle "
            "(XcodeGen output, gitignored). Edit project.yml instead and "
            "regenerate — changes here are lost on the next `xcodegen` run.",
            file=sys.stderr,
        )
        sys.exit(2)


if __name__ == "__main__":
    main()
